next.config.js, src/components/common/current-user/index.js, src/components/layout/header/index.js, src/components/pages-partials/login/index.js, src/components/ui/avatars/avatar/index.js, src/components/ui/dropdown-user/index.js, src/components/ui/forms/login-form/index.js, src/firebase/config.js, src/firebase/utils.js, src/hooks/useAuthProtection.js, src/utils/index.js, src/utils/protectedRoute.js
closes https://app.clickup.com/t/3bufjrj
=> CU-3bufjrj - Login Page Functionality

src/components/pages-partials/login/index.js, src/components/pages-partials/user-settings/index.js, src/firebase/utils.js, src/redux/slices/user.js
google login made cleaner and redirect fix
=> google auth

src/components/ui/dropdown-user/index.js
closes https://app.clickup.com/t/85zrntmqf
=> small fixes

src/components/pages-partials/single-nft/nft-detail/index.js, src/firebase/utils.js, src/pages/user/[slug].js
closes https://app.clickup.com/t/85zrncyum
=> fix 404 error on user detail page

src/components/ui/cards/products-carousel-card/index.js, src/hooks/useTokenDetails.js
closes https://app.clickup.com/t/85zrnz4x5
=> fix network error on profile page

src/components/pages-partials/user-overview/content/index.js, src/components/pages-partials/user-overview/index.js, src/components/ui/cards/products-carousel-card/index.js, src/hooks/useTokenDetails.js
closes https://app.clickup.com/t/85zrntwvh
=> fix destroy token issue

src/components/pages-partials/user-settings/wallet/index.js, src/hooks/usePriceConverter.js, src/services/relysia-socket.js
closes https://app.clickup.com/t/85zrp0hjc
=> fixed balance/history runtime update

src/hooks/usePriceConverter.js
closes https://app.clickup.com/t/85zrnwaxz
=> fixed discover page 500 error

src/components/pages-partials/user-settings/wallet/index.js, src/firebase/utils.js, src/hooks/usePriceConverter.js
closes https://app.clickup.com/t/85zrp0hjc
=> fix balance not updated on receiver end

src/components/common/protected-route/index.js, src/components/pages-partials/login/index.js, src/components/pages-partials/register/details/index.js, src/components/pages-partials/register/details/validationScheme.js, src/components/pages-partials/register/index.js, src/components/pages-partials/register/upload-photo/index.js, src/firebase/utils.js
closes https://app.clickup.com/t/85zrnby9c
=> add onboarding steps while social sign-up

src/components/ui/dropdown-user/index.js
closes https://app.clickup.com/t/85zrp2u35
=> fix reloading symbol over the supporting text

src/components/pages-partials/user-settings/wallet/index.js
closes https://app.clickup.com/t/85zrpjnq4
=> fix user wallet refresh icon position

src/components/ui/card-like-button/index.js, src/components/ui/cards/products-carousel-card/index.js, src/components/ui/forms/settings-forms/upload-form/index.js, tailwind.config.js
closes https://app.clickup.com/t/85zrk7b9b
=> show new minted nft at run time

src/components/ui/cards/products-carousel-card/index.js
closes https://app.clickup.com/t/85zrq0zbx
=> fix image ratio

src/components/pages-partials/user-overview/header/index.js
closes https://app.clickup.com/t/85zrq7ej7
=> fix avatar loader position

src/components/ui/cards/token-card/index.js, src/pages/discover/index.js, src/redux/slices/user.js
closes https://app.clickup.com/t/85zrq098k
=> fix Delisted nft not disappear on runtime

src/components/ui/forms/settings-forms/my-profile-form/index.js, tailwind.config.js
closes https://app.clickup.com/t/85zrpvrc3
=> fix checkbox color

src/components/ui/cards/token-card/index.js, src/components/ui/modal-nft-sell/index.js, src/components/ui/nft-sell-form/index.js
closes https://app.clickup.com/t/85zrqnrc7
=> fix live tag not showing on runtime on user collection

src/components/common/protected-route/index.js, src/components/pages-partials/register/index.js, src/components/ui/avatar-upload/index.js, src/components/ui/cards/profile-header-card/index.js, src/components/ui/dropdown-user/index.js
closes https://app.clickup.com/t/8669pwbjk
=> Social login tweaks

src/components/pages-partials/register/index.js, src/firebase/utils.js
closes https://app.clickup.com/t/8669pwbjk
=> fix social login redirect issue

src/components/pages-partials/user-settings/wallet/index.js
closes https://app.clickup.com/t/85zrr4vq4
=> fix profile update message appears automatically

src/components/pages-partials/register/upload-photo/index.js, src/firebase/utils.js
closes https://app.clickup.com/t/8669pwbjk
=> social login flow fixes

src/components/pages-partials/user-settings/mfa/index.js
closes https://app.clickup.com/t/85zrrujf9
=> MFA-Hide the phone number placeholder

src/pages/user/[slug].js
closes https://app.clickup.com/t/85zrtnqu8
=> fix liked artworks are not showing

next.config.js, src/components/pages-partials/discover/nft-marketplace/pagination/index.js, src/components/pages-partials/user-settings/collection/tokenDetailGrid/index.js, src/components/ui/cards/token-card/index.js, src/components/ui/cards/token-info-card/index.js, src/components/ui/modal-nft-sell/index.js, src/components/ui/nft-sell-form/index.js, src/firebase/utils.js, src/hooks/useNFTs.js, src/hooks/useTokens.js
Changed implementation of collection page
=> Collection fixes
